"""Deterministic Rust generation from the sole editable proposed vocabulary."""
import hashlib
import json
from pathlib import Path
from migrate_vocab import unique, validate

R = Path(__file__).resolve().parents[2]
source = R / "schemas/proposed/pser-0.7/content-vocabulary.json"
v = json.loads(source.read_bytes(), object_pairs_hook=unique)
validate(v)
def string(s):
    return json.dumps(s, ensure_ascii=True)
def array(a):
    return "&[" + ",".join(string(x) for x in a) + "]"
lines = [
    "// Generated by tools/proposed07/generate.py. DO NOT EDIT.",
    "// Local technical derivative; see schemas/proposed/pser-0.7/ORIGIN.md.",
    f'pub const VOCAB_SHA256: &str = "{hashlib.sha256(source.read_bytes()).hexdigest()}";',
    f"pub const PARTIES: &[&str] = {array(v['assertedBy'])};",
    f"pub const BASES: &[&str] = {array(v['basis'])};",
    f"pub const EVIDENCE_REQUIRED: &[&str] = {array(v['globalRules']['evidenceRequiredByParty'])};",
    "pub const PARTY_BASES: &[(&str, &[&str])] = &[" +
    ",".join(f"({string(k)},{array(bs)})" for k, bs in v["globalRules"]["basisByParty"].items()) + "];",
    "pub static FACTS: &[FactRule] = &[",
]
for f in v["facts"]:
    pairs = "&[" + ",".join(f"({string(p)},{string(b)})" for p,b in f.get("pairsForbidden", [])) + "]"
    unit = "None" if f["unit"] is None else f"Some({string(f['unit'])})"
    lines.append("FactRule{" + f"name:{string(f['name'])}, parties:{array(f['assertedBy'])},"
                 f"bases:{array(f['basis'])}, forbidden:{pairs}, unit:{unit},"
                 f"evidence_required:{str(f['evidence']=='required').lower()},"
                 f"remote_required:{str(f['remoteOrigin']=='required').lower()},"
                 f"value_json:{string(json.dumps(f['value'],sort_keys=True,separators=(',',':')))}" + "},")
lines.append("];")
(R / "crates/pask-wire/src/proposed_vocabulary_generated.rs").write_text("\n".join(lines) + "\n")
print("Generated 46 fact rules; source SHA-256", hashlib.sha256(source.read_bytes()).hexdigest())
